# Generated by Django 5.1.2 on 2025-02-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=55)),
                ('hpp', models.IntegerField(max_length=10)),
                ('selling_price', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
